version: '3.8'

services:
  db:
    image: postgis/postgis:13-3.1
    container_name: school-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: school
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  importer:
    image: python:3.10-slim
    container_name: dxf-importer
    depends_on:
      - db
    working_dir: /work
    volumes:
      - ../scripts:/work/scripts
      - ../scripts/utils/Grundriss_HTL_Vorlage.dxf:/work/Grundriss.dxf
    entrypoint: [ "bash", "-c" ]
    command: >
      pip install ezdxf psycopg2-binary &&
      until pg_isready -h db -U postgres; do sleep 1; done &&
      python /work/scripts/import_dxf.py /work/Grundriss.dxf &&
      echo "✅ DXF‑Import abgeschlossen." &&
      exit 0
    restart: "no"

volumes:
  db-data:
