INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (1, NULL, 'U01', 'Hall (Basement)', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (2, NULL, 'U02', 'Hallway (Left)', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (183, NULL, 'U02', 'Hallway (Up)', 'West');
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (3, NULL, 'U03', 'Storage Room', 'North');
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (4, 'BioLab', 'U04', 'Laboratory', 'North');
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (5, 'BioLab', 'U04B', 'Laboratory', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (6, NULL, 'U05', 'Storage', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (7, NULL, 'U07', 'Plastics', 'East');
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (8, NULL, 'U08', 'Telecommunications', 'West');
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (9, NULL, 'U08A', 'Computer Network Technology', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (10, NULL, 'U08B', 'Network Technology', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (11, NULL, 'U10', 'IT Room', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (12, NULL, 'U11', 'Teachers Restroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (13, NULL, 'U14', 'Womens Restroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (14, NULL, 'U16', 'Disabled Restroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (15, NULL, 'U26', 'Shelter', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (16, NULL, 'U39', 'Hallway (Up)', 'South');
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (184, NULL, 'U39', 'Hallway (Left)', 'North');
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (17, NULL, 'U41', 'Shelter', 'West');
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (18, NULL, 'U58', 'Changing Room', 'East');
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (19, NULL, 'U66', 'Womens Restroom', 'West');
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (20, NULL, 'U64', 'Mens Restroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (21, NULL, 'U70', 'Radio Station', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (22, NULL, 'U71', 'High Frequency', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (23, NULL, 'U72', 'Technical Informatics', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (24, NULL, 'U73', 'Control Technology', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (25, NULL, 'U74', 'Electrical Device Manufacturing', 'North');
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (26, NULL, 'U77', 'HF Technology', 'South');
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (27, NULL, 'U78', 'Print Manufacturing', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (28, NULL, 'U79', 'Welding', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (29, NULL, 'U81', 'Control Engineering', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (30, NULL, 'U82A', 'Computer Room1', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (31, NULL, 'U82B', 'Computer Room2', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (32, NULL, 'U83', 'Low-Frequency Technology', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (33, NULL, 'U84A', 'Electrical Installation', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (34, NULL, 'U84B', 'Basic Electrical Training', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (35, NULL, 'U85', 'Electronics B', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (36, NULL, 'U86A', 'Work Preparation', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (37, NULL, 'U86B', 'Programming', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (38, NULL, 'U87', 'Precision Engineering', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (39, NULL, 'U88', 'Mechanics', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (40, NULL, 'U89', 'Basic Mechanical Training', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (41, NULL, 'U90', 'Magazine', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (42, NULL, 'U91', 'Workshop Manager', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (43, NULL, 'U92', 'Teachers Lounge', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (46, NULL, 'E02', 'Hall (Ground Floor)', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (47, NULL, 'E03', 'School Caretaker', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (48, NULL, 'E04', 'Hallway (Left)', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (185, NULL, 'E04', 'Hallway (Down)', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (49, NULL, 'E05', 'Teachers Lounge', 'West');
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (50, NULL, 'E06', 'Teachers Lounge', 'South');
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (51, 'Marie Curie', 'E07', 'Chemistry Room', 'North');
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (52, NULL, 'E08', 'Teachers Lounge', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (53, 'Lise Meitner', 'E09', 'Physics Room', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (54, NULL, 'E10', 'Classroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (55, NULL, 'E11', 'Classroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (56, NULL, 'E13', 'Mens Restroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (57, NULL, 'E16', 'Teachers Restroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (58, NULL, 'E18', 'Disabled Restroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (59, NULL, 'E19', 'Cleaning Closet', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (60, NULL, 'E20', 'Womens Restroom', 'South');
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (61, NULL, 'E22', 'Classroom', 'West');
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (62, NULL, 'E23', 'Classroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (63, NULL, 'E24', 'Classroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (64, NULL, 'E25', 'Classroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (65, NULL, 'E26', 'Classroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (66, NULL, 'E30', 'Hallway (Up)', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (186, NULL, 'E30', 'Hallway (right)', 'East');
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (67, NULL, 'E31', 'Teachers Lounge', 'North');
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (68, NULL, 'E32', 'Teachers Lounge', 'East');
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (69, NULL, 'E33', 'Recreation Room', 'West');
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (70, NULL, 'E35', 'Administration Office', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (71, NULL, 'E36', 'Administration Office', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (72, NULL, 'E37', 'Principal', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (73, 'Johannes Kepler', 'E38+39', 'Administration Office', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (77, NULL, 'E43', 'Teachers Restroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (78, NULL, 'E45+46', 'Disabled Restroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (79, NULL, 'E50', 'Teachers Lounge', 'East');
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (80, NULL, 'E51', 'Teachers Lounge', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (81, NULL, 'E52', 'Department Head (IT)', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (82, NULL, 'E53+54', 'Teachers Lounge', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (83, NULL, 'E55', 'Department Head (ET)', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (84, NULL, 'E56', 'Storage Room', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (85, NULL, 'E57', 'Canteen', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (86, 'Edsger Dijkstra', 'E58-1', 'IT Room 11', 'South');
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (87, NULL, 'E58-2', 'Classroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (88, NULL, 'E59', 'Classroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (89, NULL, 'E60', 'Mens Restroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (90, NULL, 'E62', 'Womens Restroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (91, NULL, 'E71', 'Classroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (92, NULL, 'E72', 'Classroom', 'North');
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (93, 'Margaret Hamilton', 'E73-a', 'IT Room 7', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (94, NULL, 'E74', 'Teachers Lounge', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (95, NULL, 'T1', 'Hallway (Gyms)', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (96, NULL, 'T2', 'School Doctor', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (97, NULL, 'T05', 'Old HTL Gym', 'East');
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (98, NULL, 'T10', 'New HTL Gym', 'North');
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (99, NULL, 'T18', 'Storage', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (100, NULL, 'T21', 'Storage', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (102, NULL, '101', 'Hall (1st Floor)', 'South');
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (103, NULL, '102', 'Hallway (left)', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (104, NULL, '103', 'Teachers Lounge', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (105, NULL, '104', 'Classroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (106, NULL, '105', 'Classroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (107, NULL, '106', 'Classroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (108, NULL, '107', 'Classroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (109, 'Ada Lovelace', '108-a', 'IT Room 2', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (110, 'Don Knuth', '109-a', 'IT Room 1', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (111, NULL, '110', 'Mens Restroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (112, NULL, '114', 'Teachers Restroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (113, NULL, '115', 'Disabled Restroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (114, NULL, '116', 'Cleaning Closet', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (115, NULL, '118', 'Womens Restroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (116, NULL, '119', 'Classroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (117, NULL, '120', 'Classroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (118, 'Niklaus Wirth', '121', 'IT Room3', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (119, 'Grace Hopper', '122', 'IT Room 4', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (120, 'Brian Kernighan', '123', 'IT Room 5', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (121, NULL, '124', 'System Administration', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (122, NULL, '130', 'Hallway (right)', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (123, NULL, '131', 'Sound Room', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (124, NULL, '132', 'Classroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (125, NULL, '133', 'Classroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (126, NULL, '134', 'Classroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (127, 'Barbara Liskov', '135', 'IT Room 10', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (128, NULL, '136', 'Mens Restroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (129, NULL, '138', 'Cleaning Closet', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (130, NULL, '139', 'Teachers Restroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (131, NULL, '140', 'Womens Restroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (132, NULL, '142', 'Teachers Lounge', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (133, NULL, '143a', 'IT Room', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (134, NULL, '143b', 'IT Room', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (135, NULL, '144', 'IT Room', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (136, NULL, '145', 'Classroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (137, NULL, '146', 'Classroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (138, NULL, '147', 'Classroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (139, NULL, '148', 'Teachers Lounge', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (140, NULL, '151', 'Classroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (141, NULL, '152', 'Classroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (142, NULL, '153', 'Classroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (143, NULL, '154', 'Classroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (145, NULL, '201', 'Hall (2nd Floor)', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (146, NULL, '202', 'Hallway (left)', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (147, NULL, '203', 'Teachers Lounge', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (148, NULL, '204', 'Classroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (149, NULL, '205', 'Teachers Lounge', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (150, NULL, '206', 'Teachers Lounge', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (151, NULL, '208', 'Teachers Restroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (152, NULL, '209', 'Mens Restroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (153, NULL, '212', 'Womens Restroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (154, NULL, '213', 'Classroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (155, NULL, '214', 'Classroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (156, NULL, '215', 'Classroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (157, NULL, '216', 'Classroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (158, NULL, '217', 'Classroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (159, NULL, '218', 'Teachers Lounge', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (160, NULL, '220', 'Teachers Lounge', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (161, NULL, '221', 'Teachers Lounge', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (162, NULL, '222', 'Teachers Lounge', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (163, NULL, '223', 'Teachers Lounge', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (164, NULL, '224', 'Teachers Lounge', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (165, NULL, '225', 'Hallway (right)', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (166, NULL, '226', 'Teachers Lounge', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (167, NULL, '227', 'Classroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (168, NULL, '228', 'Classroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (169, NULL, '229', 'Classroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (170, NULL, '230', 'Classroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (171, NULL, '231', 'Classroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (172, NULL, '232', 'Mens Restroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (173, NULL, '236', 'Womens Restroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (174, NULL, '237', 'Teachers Lounge', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (175, NULL, '238', 'Classroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (176, NULL, '239', 'Study Group Room', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (177, NULL, '240', 'Small Chamber', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (178, NULL, '241', 'Teachers Lounge', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (179, NULL, '251', 'Classroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (180, NULL, '252', 'Classroom', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (181, 'Steve Wozniak', '253-a', 'IT Room 8', NULL);
INSERT INTO room (roomid, roomlabel, roomname, roomtype, direction) VALUES (182, NULL, '254', 'Teachers Lounge', NULL);

commit;

UPDATE room SET neighbouroutside = 3 WHERE roomid = 1;
UPDATE room SET corridor = 2, neighbourinside = 1, neighbouroutside = 4 WHERE roomid = 3;
UPDATE room SET corridor = 2, neighbourinside = 3, neighbouroutside = 5 WHERE roomid = 4;
UPDATE room SET corridor = 2, neighbourinside = 4, neighbouroutside = 6 WHERE roomid = 5;
UPDATE room SET corridor = 183, neighbourinside = 5, neighbouroutside = 41 WHERE roomid = 6;
UPDATE room SET corridor = 183, neighbouroutside = 40 WHERE roomid = 7;
UPDATE room SET corridor = 2, neighbourinside = 11, neighbouroutside = 9 WHERE roomid = 8;
UPDATE room SET corridor = 2, neighbourinside = 8, neighbouroutside = 10 WHERE roomid = 9;
UPDATE room SET corridor = 2, neighbourinside = 9 WHERE roomid = 10;
UPDATE room SET corridor = 2, neighbourinside = 12, neighbouroutside = 8 WHERE roomid = 11;
UPDATE room SET corridor = 2, neighbourinside = 13, neighbouroutside = 11 WHERE roomid = 12;
UPDATE room SET corridor = 2, neighbourinside = 14, neighbouroutside = 12 WHERE roomid = 13;
UPDATE room SET corridor = 2, neighbourinside = 15, neighbouroutside = 13 WHERE roomid = 14;
UPDATE room SET corridor = 2, neighbourinside = 1, neighbouroutside = 14 WHERE roomid = 15;
UPDATE room SET corridor = 16, neighbourinside = 1, neighbouroutside = 19 WHERE roomid = 17;
UPDATE room SET corridor = 16, neighbourinside = 1, neighbouroutside = 25 WHERE roomid = 18;
UPDATE room SET corridor = 16, neighbourinside = 17, neighbouroutside = 20 WHERE roomid = 19;
UPDATE room SET corridor = 16, neighbourinside = 19, neighbouroutside = 21 WHERE roomid = 20;
UPDATE room SET corridor = 16, neighbourinside = 20, neighbouroutside = 21 WHERE roomid = 21;
UPDATE room SET corridor = 16, neighbourinside = 21, neighbouroutside = 22 WHERE roomid = 22;
UPDATE room SET corridor = 16, neighbourinside = 22 WHERE roomid = 23;
UPDATE room SET corridor = 184, neighbourinside = 29 WHERE roomid = 24;
UPDATE room SET corridor = 184, neighbourinside = 18, neighbouroutside = 26 WHERE roomid = 25;
UPDATE room SET corridor = 184, neighbourinside = 27, neighbouroutside = 25 WHERE roomid = 26;
UPDATE room SET corridor = 184, neighbourinside = 28, neighbouroutside = 26 WHERE roomid = 27;
UPDATE room SET corridor = 184, neighbouroutside = 27 WHERE roomid = 28;
UPDATE room SET corridor = 184, neighbourinside = 30, neighbouroutside = 24 WHERE roomid = 29;
UPDATE room SET corridor = 184, neighbourinside = 31, neighbouroutside = 29 WHERE roomid = 30;
UPDATE room SET corridor = 184, neighbourinside = 32, neighbouroutside = 30 WHERE roomid = 31;
UPDATE room SET corridor = 184, neighbourinside = 33, neighbouroutside = 31 WHERE roomid = 32;
UPDATE room SET corridor = 184, neighbourinside = 34, neighbouroutside = 32 WHERE roomid = 33;
UPDATE room SET corridor = 184, neighbourinside = 35, neighbouroutside = 33 WHERE roomid = 34;
UPDATE room SET corridor = 184, neighbourinside = 36, neighbouroutside = 34 WHERE roomid = 35;
UPDATE room SET corridor = 184, neighbourinside = 37, neighbouroutside = 35 WHERE roomid = 36;
UPDATE room SET corridor = 184, neighbourinside = 38, neighbouroutside = 36 WHERE roomid = 37;
UPDATE room SET corridor = 183, neighbouroutside = 39 WHERE roomid = 38;
UPDATE room SET corridor = 183, neighbourinside = 38, neighbouroutside = 40 WHERE roomid = 39;
UPDATE room SET corridor = 183, neighbourinside = 39, neighbouroutside = 7 WHERE roomid = 40;
UPDATE room SET corridor = 183, neighbourinside = 42, neighbouroutside = 6 WHERE roomid = 41;
UPDATE room SET corridor = 183, neighbourinside = 43, neighbouroutside = 41 WHERE roomid = 42;
UPDATE room SET corridor = 183, neighbouroutside = 42 WHERE roomid = 43;
UPDATE room SET neighbouroutside = 49 WHERE roomid = 46;
UPDATE room SET neighbouroutside = 46 WHERE roomid = 47;
UPDATE room SET corridor = 48, neighbourinside = 46, neighbouroutside = 50 WHERE roomid = 49;
UPDATE room SET corridor = 48, neighbourinside = 49, neighbouroutside = 51 WHERE roomid = 50;
UPDATE room SET corridor = 48, neighbourinside = 50, neighbouroutside = 52 WHERE roomid = 51;
UPDATE room SET corridor = 48, neighbourinside = 51, neighbouroutside = 53 WHERE roomid = 52;
UPDATE room SET corridor = 48, neighbourinside = 52 WHERE roomid = 53;
UPDATE room SET corridor = 48, neighbouroutside = 55 WHERE roomid = 54;
UPDATE room SET corridor = 48, neighbourinside = 54, neighbouroutside = 56 WHERE roomid = 55;
UPDATE room SET corridor = 48, neighbourinside = 55, neighbouroutside = 57 WHERE roomid = 56;
UPDATE room SET corridor = 48, neighbourinside = 56, neighbouroutside = 58 WHERE roomid = 57;
UPDATE room SET corridor = 48, neighbourinside = 57 WHERE roomid = 58;
UPDATE room SET corridor = 185, neighbouroutside = 60 WHERE roomid = 59;
UPDATE room SET corridor = 185, neighbourinside = 59, neighbouroutside = 61 WHERE roomid = 60;
UPDATE room SET corridor = 185, neighbourinside = 60, neighbouroutside = 61 WHERE roomid = 61;
UPDATE room SET corridor = 185, neighbourinside = 60, neighbouroutside = 94 WHERE roomid = 62;
UPDATE room SET corridor = 185, neighbourinside = 64, neighbouroutside = 91 WHERE roomid = 63;
UPDATE room SET corridor = 185, neighbourinside = 65, neighbouroutside = 62 WHERE roomid = 64;
UPDATE room SET corridor = 185, neighbouroutside = 63 WHERE roomid = 65;
UPDATE room SET corridor = 66, neighbourinside = 46, neighbouroutside = 68 WHERE roomid = 67;
UPDATE room SET corridor = 66, neighbourinside = 67, neighbouroutside = 69 WHERE roomid = 68;
UPDATE room SET corridor = 66, neighbourinside = 68, neighbouroutside = 70 WHERE roomid = 69;
UPDATE room SET corridor = 66, neighbourinside = 69, neighbouroutside = 71 WHERE roomid = 70;
UPDATE room SET corridor = 66, neighbourinside = 70, neighbouroutside = 72 WHERE roomid = 71;
UPDATE room SET corridor = 66, neighbourinside = 71, neighbouroutside = 73 WHERE roomid = 72;
UPDATE room SET corridor = 66, neighbourinside = 72 WHERE roomid = 73;
UPDATE room SET corridor = 66, neighbouroutside = 78 WHERE roomid = 77;
UPDATE room SET corridor = 66, neighbourinside = 77, neighbouroutside = 79 WHERE roomid = 78;
UPDATE room SET corridor = 66, neighbourinside = 78, neighbouroutside = 80 WHERE roomid = 79;
UPDATE room SET corridor = 66, neighbourinside = 79, neighbouroutside = 81 WHERE roomid = 80;
UPDATE room SET corridor = 66, neighbourinside = 80, neighbouroutside = 82 WHERE roomid = 81;
UPDATE room SET corridor = 66, neighbourinside = 81, neighbouroutside = 83 WHERE roomid = 82;
UPDATE room SET corridor = 66, neighbourinside = 82 WHERE roomid = 83;
UPDATE room SET corridor = 186, neighbouroutside = 85 WHERE roomid = 84;
UPDATE room SET corridor = 186, neighbourinside = 84, neighbouroutside = 86 WHERE roomid = 85;
UPDATE room SET corridor = 186, neighbourinside = 85, neighbouroutside = 87 WHERE roomid = 86;
UPDATE room SET corridor = 186, neighbourinside = 86 WHERE roomid = 87;
UPDATE room SET corridor = 186, neighbourinside = 89 WHERE roomid = 88;
UPDATE room SET corridor = 186, neighbourinside = 90, neighbouroutside = 88 WHERE roomid = 89;
UPDATE room SET corridor = 186, neighbouroutside = 89 WHERE roomid = 90;
UPDATE room SET corridor = 48, neighbourinside = 63, neighbouroutside = 92 WHERE roomid = 91;
UPDATE room SET corridor = 48, neighbourinside = 91 WHERE roomid = 92;
UPDATE room SET corridor = 48, neighbourinside = 94 WHERE roomid = 93;
UPDATE room SET corridor = 48, neighbourinside = 62, neighbouroutside = 93 WHERE roomid = 94;
UPDATE room SET corridor = 95, neighbouroutside = 97 WHERE roomid = 96;
UPDATE room SET corridor = 95, neighbourinside = 96, neighbouroutside = 98 WHERE roomid = 97;
UPDATE room SET corridor = 95, neighbourinside = 97 WHERE roomid = 98;
UPDATE room SET corridor = 95, neighbouroutside = 100 WHERE roomid = 99;
UPDATE room SET corridor = 95, neighbourinside = 99 WHERE roomid = 100;
UPDATE room SET neighbourinside = 139, neighbouroutside = 104 WHERE roomid = 102;
UPDATE room SET corridor = 103, neighbourinside = 102, neighbouroutside = 105 WHERE roomid = 104;
UPDATE room SET corridor = 103, neighbourinside = 104, neighbouroutside = 106 WHERE roomid = 105;
UPDATE room SET corridor = 103, neighbourinside = 105, neighbouroutside = 107 WHERE roomid = 106;
UPDATE room SET corridor = 103, neighbourinside = 106, neighbouroutside = 108 WHERE roomid = 107;
UPDATE room SET corridor = 103, neighbourinside = 107 WHERE roomid = 108;
UPDATE room SET corridor = 103, neighbourinside = 110 WHERE roomid = 109;
UPDATE room SET corridor = 103, neighbourinside = 111, neighbouroutside = 109 WHERE roomid = 110;
UPDATE room SET corridor = 103, neighbourinside = 112, neighbouroutside = 110 WHERE roomid = 111;
UPDATE room SET corridor = 103, neighbourinside = 113, neighbouroutside = 111 WHERE roomid = 112;
UPDATE room SET corridor = 103, neighbouroutside = 112 WHERE roomid = 113;
UPDATE room SET corridor = 103, neighbouroutside = 115 WHERE roomid = 114;
UPDATE room SET corridor = 103, neighbourinside = 114, neighbouroutside = 116 WHERE roomid = 115;
UPDATE room SET corridor = 103, neighbourinside = 115, neighbouroutside = 117 WHERE roomid = 116;
UPDATE room SET corridor = 103, neighbourinside = 116, neighbouroutside = 143 WHERE roomid = 117;
UPDATE room SET corridor = 103, neighbourinside = 119, neighbouroutside = 140 WHERE roomid = 118;
UPDATE room SET corridor = 103, neighbourinside = 120, neighbouroutside = 118 WHERE roomid = 119;
UPDATE room SET corridor = 103, neighbourinside = 121, neighbouroutside = 119 WHERE roomid = 120;
UPDATE room SET corridor = 103, neighbourinside = 102, neighbouroutside = 120 WHERE roomid = 121;
UPDATE room SET corridor = 122, neighbourinside = 102, neighbouroutside = 124 WHERE roomid = 123;
UPDATE room SET corridor = 122, neighbourinside = 123, neighbouroutside = 125 WHERE roomid = 124;
UPDATE room SET corridor = 122, neighbourinside = 124, neighbouroutside = 126 WHERE roomid = 125;
UPDATE room SET corridor = 122, neighbourinside = 125 WHERE roomid = 126;
UPDATE room SET corridor = 122, neighbourinside = 128 WHERE roomid = 127;
UPDATE room SET corridor = 122, neighbourinside = 129, neighbouroutside = 127 WHERE roomid = 128;
UPDATE room SET corridor = 122, neighbouroutside = 128 WHERE roomid = 129;
UPDATE room SET corridor = 122, neighbouroutside = 131 WHERE roomid = 130;
UPDATE room SET corridor = 122, neighbourinside = 130, neighbouroutside = 132 WHERE roomid = 131;
UPDATE room SET corridor = 122, neighbourinside = 131, neighbouroutside = 133 WHERE roomid = 132;
UPDATE room SET corridor = 122, neighbourinside = 132, neighbouroutside = 134 WHERE roomid = 133;
UPDATE room SET corridor = 122, neighbourinside = 133 WHERE roomid = 134;
UPDATE room SET corridor = 122, neighbourinside = 136 WHERE roomid = 135;
UPDATE room SET corridor = 122, neighbourinside = 137, neighbouroutside = 135 WHERE roomid = 136;
UPDATE room SET corridor = 122, neighbourinside = 138, neighbouroutside = 136 WHERE roomid = 137;
UPDATE room SET corridor = 122, neighbourinside = 139, neighbouroutside = 137 WHERE roomid = 138;
UPDATE room SET corridor = 122, neighbourinside = 102, neighbouroutside = 138 WHERE roomid = 139;
UPDATE room SET corridor = 103, neighbourinside = 118, neighbouroutside = 141 WHERE roomid = 140;
UPDATE room SET corridor = 103, neighbourinside = 140 WHERE roomid = 141;
UPDATE room SET corridor = 103, neighbourinside = 143 WHERE roomid = 142;
UPDATE room SET corridor = 103, neighbourinside = 117, neighbouroutside = 142 WHERE roomid = 143;
UPDATE room SET neighbouroutside = 147 WHERE roomid = 145;
UPDATE room SET corridor = 146, neighbourinside = 145, neighbouroutside = 148 WHERE roomid = 147;
UPDATE room SET corridor = 146, neighbourinside = 147, neighbouroutside = 149 WHERE roomid = 148;
UPDATE room SET corridor = 146, neighbourinside = 148 WHERE roomid = 149;
UPDATE room SET corridor = 146, neighbourinside = 148, neighbouroutside = 151 WHERE roomid = 150;
UPDATE room SET corridor = 146, neighbourinside = 150 WHERE roomid = 151;
UPDATE room SET corridor = 146, neighbouroutside = 153 WHERE roomid = 152;
UPDATE room SET corridor = 146, neighbourinside = 152, neighbouroutside = 154 WHERE roomid = 153;
UPDATE room SET corridor = 146, neighbourinside = 153, neighbouroutside = 155 WHERE roomid = 154;
UPDATE room SET corridor = 146, neighbourinside = 154, neighbouroutside = 182 WHERE roomid = 155;
UPDATE room SET corridor = 146, neighbourinside = 157, neighbouroutside = 179 WHERE roomid = 156;
UPDATE room SET corridor = 146, neighbourinside = 158, neighbouroutside = 156 WHERE roomid = 157;
UPDATE room SET corridor = 146, neighbourinside = 159, neighbouroutside = 157 WHERE roomid = 158;
UPDATE room SET corridor = 146, neighbourinside = 160, neighbouroutside = 158 WHERE roomid = 159;
UPDATE room SET corridor = 145, neighbourinside = 161, neighbouroutside = 159 WHERE roomid = 160;
UPDATE room SET corridor = 145, neighbourinside = 162, neighbouroutside = 160 WHERE roomid = 161;
UPDATE room SET corridor = 145, neighbourinside = 163, neighbouroutside = 161 WHERE roomid = 162;
UPDATE room SET corridor = 145, neighbourinside = 162, neighbouroutside = 164 WHERE roomid = 163;
UPDATE room SET corridor = 145, neighbourinside = 163, neighbouroutside = 166 WHERE roomid = 164;
UPDATE room SET corridor = 165, neighbourinside = 164, neighbouroutside = 167 WHERE roomid = 166;
UPDATE room SET corridor = 165, neighbourinside = 166, neighbouroutside = 168 WHERE roomid = 167;
UPDATE room SET corridor = 165, neighbourinside = 167, neighbouroutside = 169 WHERE roomid = 168;
UPDATE room SET corridor = 165, neighbourinside = 168 WHERE roomid = 169;
UPDATE room SET corridor = 165, neighbourinside = 171 WHERE roomid = 170;
UPDATE room SET corridor = 165, neighbourinside = 172, neighbouroutside = 170 WHERE roomid = 171;
UPDATE room SET corridor = 165, neighbourinside = 173, neighbouroutside = 171 WHERE roomid = 172;
UPDATE room SET corridor = 165, neighbouroutside = 172 WHERE roomid = 173;
UPDATE room SET corridor = 165, neighbourinside = 175 WHERE roomid = 174;
UPDATE room SET corridor = 165, neighbourinside = 176, neighbouroutside = 174 WHERE roomid = 175;
UPDATE room SET corridor = 165, neighbourinside = 177, neighbouroutside = 175 WHERE roomid = 176;
UPDATE room SET corridor = 165, neighbourinside = 178, neighbouroutside = 176 WHERE roomid = 177;
UPDATE room SET corridor = 165, neighbourinside = 145, neighbouroutside = 177 WHERE roomid = 178;
UPDATE room SET corridor = 146, neighbourinside = 156, neighbouroutside = 180 WHERE roomid = 179;
UPDATE room SET corridor = 146, neighbourinside = 179 WHERE roomid = 180;
UPDATE room SET corridor = 146, neighbourinside = 182 WHERE roomid = 181;
UPDATE room SET corridor = 146, neighbourinside = 155, neighbouroutside = 181 WHERE roomid = 182;