name: Render PlantUML Diagrams

on:
  push:
    paths:
      - 'Documentation/SystemArchitecture/SystemArchitecture.adoc'
  pull_request:
    paths:
      - 'Documentation/SystemArchitecture/SystemArchitecture.adoc'

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install PlantUML
        run: |
          sudo apt-get update
          sudo apt-get install plantuml

      - name: Render PlantUML diagrams to SVG
        run: |
          mkdir -p Documentation/SystemArchitecture/diagrams  # Erstelle den Ordner für das Diagramm
          plantuml -tsvg Documentation/SystemArchitecture/SystemArchitecture.adoc  # Generiere das SVG-Diagramm
          mv Documentation/SystemArchitecture/*.svg Documentation/SystemArchitecture/diagrams/

      - name: Debug GitHub Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote -v  # Zeigt die Remote-URL an
          git branch  # Zeigt den aktuellen Branch an
          git status  # Zeigt den Status der Änderungen
          git add Documentation/SystemArchitecture/diagrams/*.svg
          git commit -m "docs: Update PlantUML diagram"
          git push https://x-access-token:${{ secrets.MY_GITHUB_PUSH_TOKEN }}@github.com/${{ github.repository }} HEAD:main