name: Render PlantUML Diagrams

on:
  push:
    paths:
      - 'Documentation/SystemArchitecture/SystemArchitecture.adoc'
  pull_request:
    paths:
      - 'Documentation/SystemArchitecture/SystemArchitecture.adoc'

jobs:
  render:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Stellt sicher, dass GITHUB_TOKEN Schreibrechte hat

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install PlantUML
        run: |
          sudo apt-get update
          sudo apt-get install -y plantuml

      - name: Render PlantUML diagrams to SVG
        run: |
          mkdir -p Documentation/SystemArchitecture/diagrams  # Erstelle den Ordner für das Diagramm
          plantuml -tsvg Documentation/SystemArchitecture/SystemArchitecture.adoc  # Generiere das SVG-Diagramm
          mv Documentation/SystemArchitecture/*.svg Documentation/SystemArchitecture/diagrams/

      - name: Debug Remote Branches
        run: |
          git fetch --all
          git branch -r  # Zeigt Remote-Branches an

      - name: Debug GitHub Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote -v  # Zeigt die Remote-URL an
          git branch  # Zeigt den aktuellen Branch an
          git status  # Zeigt den Status der Änderungen
          git add Documentation/SystemArchitecture/diagrams/*.svg
          git commit -m "docs: Update PlantUML diagram" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:feature

      - name: Test Token Permissions
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}

      # Optionale Alternative mit PAT
      - name: Commit and push with PAT (if GITHUB_TOKEN fails)
        if: failure()  # Führe dies aus, falls vorheriger Schritt fehlschlägt
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add Documentation/SystemArchitecture/diagrams/*.svg
          git commit -m "docs: Update PlantUML diagram" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.MY_GITHUB_PUSH_TOKEN }}@github.com/${{ github.repository }} HEAD:feature
